node {
  stage('Checkout') {
    git branch: 'main', url: 'https://github.com/leoduprates/cucumber-selenium-testing'
  }
  stage('Build') {
    nodejs(nodeJSInstallationName: 'nodejs') {
      sh 'npm install'
    }
  }
  stage('Archive Artifacts') {
    archiveArtifacts artifacts: '**', onlyIfSuccessful: true
  }
}