node {
  stage('Copy Project') {
    copyArtifacts (
          projectName: 'selenium-cucumber-js',
          filter: '**'
        );
  }
  stage('Test') {
    nodejs(nodeJSInstallationName: 'nodejs') {
      sh 'BROWSER=chrome SERVER=http://selenium-hub:4444/wd/hub npm test -- -t @regression'
    }
  }
  stage('Report') {
    nodejs(nodeJSInstallationName: 'nodejs') {
      sh 'npm run report'
    }
    publishHTML (
      target : [
        allowMissing: false,
        alwaysLinkToLastBuild: true,
        keepAll: true,
        reportDir: 'reports',
        reportFiles: 'report.html',
        reportName: 'Automation Test Report',
        reportTitles: 'Automation Test Report'
      ]
    )
  }
}