Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network :forwarded_port, guest:4444, host:4444

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.memory = 2048
    virtualbox.cpus = 2
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "selenium-server.yml"
  end
end